let  value = 1;
value += 5 
console.log("Value is now = " , value)
value -= 5 
console.log("Value is now = ", value)
value *= 5          
console.log("Value is now = " , value)
value /= 5          
console.log("Value is now = ", value)